Human readbale dates and multiple file path support in the collate command
ComplianceAsCode/auditree-harvest pull request #27
Opened 2022-09-29 18:11 UTC by rhyshort

- [x] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](../blob/master/DCO1.1.txt)

## What

- Make `--start` and `--end` options in collate accept humna readable dates, ie 2022-09-29 instead of 20220929
- Enable collation of mulitple files with a single collate command by using `,` as a path seperator.

## Why

The current `--start` and `--end` formats are hard for humans to read, which makes collating data to provide to auditors difficult, as conversion between date formats needs to be done by hand, and the number grouping makes it hard to ensure there have not been any typos etc

Being able to pull multiple files at once makes it easier to pull multiple files over the same date range when an auditor is requesting multiple files.

## How

- Replace all references to `YYYYMMDD` dates to `YYYY-MM-DD` dates
- Split the file path string and iterate over the result calling collate functions multiple times.

## Test

- Updated tests for the new date format
- Add a new test to pull multiple files.

## Context

2022-09-30 11:29 UTC, drsm79 requested changes

2022-09-30 11:29 UTC, drsm79 commented on harvest/cli.py
>                  'the relative path to a file in a git repository '
I think better would be to use an `append` action, so the list is explicit

2022-09-30 11:29 UTC, drsm79 commented on harvest/cli.py
>                  'the relative path to a file in a git repository '
https://docs.python.org/3/library/argparse.html

2022-09-30 16:26 UTC, rhyshort commented on harvest/cli.py
>                  'the relative path to a file in a git repository '
`append` action wasn't doing quite the right thing with postional args, so option to use `nargs='+'`, which has the desired behaviour. Example help text: 
```
harvest collate --help
usage: harvest collate [-h] [--repo-path ~/path/git-repo] [--creds ~/path/creds] [--end YYYY-MM-DD] [--start YYYY-MM-DD] [--version] repo filepath [filepath ...]

positional arguments:
  repo                  the URL to the repository containing files to be processed by harvest, as an example: https://github.com/my-org/my-repo or: local - if working exclusively with a local git repo
  filepath              the relative path to a file in a git repository that you wish to retrieve.

optional arguments:
  -h, --help            show this help message and exit
  --repo-path ~/path/git-repo
                        the operating system location of a local git repository - if not provided, repo path is assumed to be $TMPDIR/harvest
  --creds ~/path/creds  the path to credentials file - defaults to ~/.credentials
  --end YYYY-MM-DD      the end of date range for the file you wish to retrieve - defaults to the current date
  --start YYYY-MM-DD    the start of date range for the file you wish to retrieve - defaults to same value as the end of date range
  --version             the harvest version```

2022-10-06 10:50 UTC, drsm79 commented on harvest/cli.py
> +            metavar='YYYY-MM-DD',
Sure I mentioned that this is an unnecessary breaking change. Suggest we have a function that takes a date in either YYYYMMDD or YYYY-MM-DD format and returns the datetime object for it. That will preserve current behaviour for anyone who's got a script using the tool and support both ISO date formats.

2022-12-20 16:54 UTC, rhyshort commented on harvest/cli.py
> +            metavar='YYYY-MM-DD',
took me some time to get around to it but done now

2022-12-20 23:22 UTC, drsm79 commented on harvest/cli.py
> +            metavar='YYYY-MM-DD',
Nice one

2022-12-20 23:23 UTC, drsm79 submitted a review, later dismissed

2023-01-23 10:22 UTC, drsm79 submitted a review, later dismissed

2023-01-23 16:38 UTC, rhyshort commented
hmm the github action looks like is failing because of the python version is too old for the version of flake8.

2023-01-27 15:45 UTC, cletomartin commented
@rhyshort I'm changing all the linting side of the project here #28

2023-01-27 16:27 UTC, rhyshort commented
@cletomartin nice, I'll rebase this on top of #28 once merged.

2023-02-08 10:58 UTC, rhyshort commented
Rebased on top of the changes from #28

2023-02-08 12:28 UTC, cletomartin reviewed
Thanks!

Please update the version https://github.com/ComplianceAsCode/auditree-harvest/blob/main/harvest/__init__.py#L16 and the CHANGES.md file too.

2023-02-08 15:03 UTC, rhyshort commented
Done

2023-02-09 08:55 UTC, cletomartin approved these changes

2023-02-09 12:59 UTC, rhyshort commented
Thanks @cletomartin, I don't have write access so can you go ahead and merge please?

2023-02-09 13:05 UTC, merged

2023-02-09 13:06 UTC, drsm79 commented
Merged - thanks Rhys!